package com.store.mgmt.inventory.mapper;

import com.store.mgmt.inventory.model.dto.*;
import com.store.mgmt.inventory.model.entity.Brand;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

import java.util.List;

@Mapper(componentModel = "spring",
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
public interface BrandMapper {

    BrandDTO toDto(Brand brand);
    List<BrandDTO> toDtoList(List<Brand> brands);

    @Mapping(target = "id", ignore = true) // ID is generated by JPA
    Brand toEntity(CreateBrandDTO createDTO);

    @Mapping(target = "id", ignore = true) // Don't update ID
    void updateBrandFromDto(UpdateBrandDTO updateDTO, @MappingTarget Brand brand);
}