package com.store.mgmt.inventory.mapper;
import com.store.mgmt.inventory.model.dto.CreateDiscountDTO;
import com.store.mgmt.inventory.model.dto.DiscountDTO;
import com.store.mgmt.inventory.model.dto.UpdateDiscountDTO;
import com.store.mgmt.inventory.model.entity.Discount;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

import java.util.List;

@Mapper(componentModel = "spring", nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
public interface DiscountMapper {
    // Mapstruct will automatically generate the mapping methods for Discount entity
    // to and from DTOs if you define them in the DTO classes.

    // Example method signatures (to be implemented in DTO classes):
     DiscountDTO toDto(Discount discount);
     List<DiscountDTO> toDtoList(List<Discount> discounts);
     @Mapping(target = "id", ignore = true)
     Discount toEntity(CreateDiscountDTO createDTO);
    @Mapping(target = "id", ignore = true) // ID is generated by JPA
     void updateDiscountFromDto(UpdateDiscountDTO updateDTO, @MappingTarget Discount discount);
}