package com.store.mgmt.inventory.mapper;
import com.store.mgmt.inventory.model.dto.CreateInventoryItemDTO;
import com.store.mgmt.inventory.model.dto.InventoryItemDTO;
import com.store.mgmt.inventory.model.entity.InventoryItem;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.NullValuePropertyMappingStrategy;

import java.util.List;

@Mapper(componentModel = "spring", nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
public interface InventoryItemMapper {
    // Define mapping methods here
    // For example:
    InventoryItemDTO toDto(InventoryItem entity);

    // Convert a list of InventoryItem entities to a list of InventoryItemDTOs
     List<InventoryItemDTO> toDtoList(List<InventoryItem> entities);

     // Convert CreateInventoryItemDTO to InventoryItem entity
     // ID is generated by JPA, so we ignore it in the mapping
    @Mapping(target = "id", ignore = true) // ID is generated by JPA
     InventoryItem toEntity(CreateInventoryItemDTO dto);
}