package com.store.mgmt.inventory.mapper;

import com.store.mgmt.inventory.model.dto.CreateProductDTO;
import com.store.mgmt.inventory.model.dto.ProductDTO;
import com.store.mgmt.inventory.model.dto.UpdateProductDTO;
import com.store.mgmt.inventory.model.entity.Product;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

import java.util.List;

@Mapper(componentModel = "spring",
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE) // Ignore nulls for updates
public interface ProductMapper {

    ProductDTO toDto(Product product);
    List<ProductDTO> toDtoList(List<Product> products);

    @Mapping(target = "id", ignore = true) // ID is generated by JPA
    Product toEntity(CreateProductDTO createDTO);

    // For updating an existing product from DTO
    // nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE in @Mapper annotation
    // handles fields that are null in DTO (i.e., not provided) to be ignored.
    @Mapping(target = "id", ignore = true) // Don't update ID
    void updateProductFromDto(UpdateProductDTO updateDTO, @MappingTarget Product product);
}