package com.store.mgmt.inventory.mapper;
import com.store.mgmt.inventory.model.dto.CreateSaleItemDTO;
import com.store.mgmt.inventory.model.dto.SaleItemDTO;
import com.store.mgmt.inventory.model.dto.UpdateSaleItemDTO;
import com.store.mgmt.inventory.model.entity.SaleItem;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

import java.util.List;

@Mapper(componentModel = "spring", nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
public interface SaleItemMapper {
     SaleItemDTO toDto(SaleItem saleItem);
     List<SaleItemDTO> toDtoList(List<SaleItem> saleItems);
     @Mapping(target = "id", ignore = true) // ID is generated by JPA
     SaleItem toEntity(CreateSaleItemDTO createDTO);
    @Mapping(target = "id", ignore = true) // ID is generated by JPA
     void updateSaleItemFromDto(UpdateSaleItemDTO updateDTO, @MappingTarget SaleItem saleItem);
}