package com.store.mgmt.inventory.mapper;
import com.store.mgmt.inventory.model.dto.CreateSupplierDTO;
import com.store.mgmt.inventory.model.dto.SupplierDTO;
import com.store.mgmt.inventory.model.dto.UpdateSupplierDTO;
import com.store.mgmt.inventory.model.entity.Supplier;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;

import java.util.List;

@Mapper(componentModel = "spring", nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
public interface SupplierMapper {
     SupplierDTO toDto(Supplier supplier);
     List<SupplierDTO> toDtoList(List<Supplier> suppliers);
     @Mapping(target = "id", ignore = true) // ID is generated by JPA
     Supplier toEntity(CreateSupplierDTO createDTO);
    @Mapping(target = "id", ignore = true) // ID is generated by JPA
     void updateSupplierFromDto(UpdateSupplierDTO updateDTO, @MappingTarget Supplier supplier);
}