package com.store.mgmt.inventory.model.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.math.BigDecimal;
import java.util.UUID;

@Data
@Schema(name = "UpdateProduct", description = "Data Transfer Object for a product item available for sale")
public class UpdateProductDTO extends CreateProductDTO {

    @Schema(
            description = "Unique identifier of the product",
            example = "a1b2c3d4-e5f6-7890-1234-567890abcdef",
            accessMode = Schema.AccessMode.READ_ONLY // Typically generated by the system
    )
    private UUID id;
}