--liquibase formatted sql

--changeset system:V12-seed-role-permissions
--comment: Map industry-standard permissions to roles

-- Helper: Get permission ID by name (using known UUIDs from V10)
-- SUPER_ADMIN: Full system access (all permissions)
INSERT INTO role_permissions (role_id, permission_id)
SELECT '22222222-2222-2222-2222-000000000001', id FROM permissions
WHERE name IN (
    'ORG_READ', 'ORG_WRITE', 'STORE_READ', 'STORE_WRITE',
    'PRODUCT_READ', 'PRODUCT_WRITE', 'COST_READ', 'MARGIN_READ',
    'USER_READ', 'USER_WRITE', 'USER_INVITE', 'ROLE_READ', 'ROLE_WRITE',
    'INVENTORY_ITEM_READ', 'INVENTORY_ITEM_WRITE', 'STOCK_ADJUST', 'CYCLE_COUNT', 'TRANSFER_CREATE', 'TRANSFER_APPROVE',
    'PO_READ', 'PO_WRITE', 'PO_APPROVE', 'RECEIVING_CREATE',
    'SALE_READ', 'SALE_WRITE', 'VOID_SALE', 'REFUND_APPROVE', 'PRICE_OVERRIDE', 'DISCOUNT_APPLY',
    'CASH_DRAWER_READ', 'CASH_DRAWER_WRITE', 'END_OF_DAY',
    'REPORT_READ', 'REPORT_FINANCIAL', 'REPORT_INVENTORY',
    'CATEGORY_READ', 'CATEGORY_WRITE', 'BRAND_READ', 'BRAND_WRITE',
    'SUPPLIER_READ', 'SUPPLIER_WRITE', 'LOCATION_READ', 'LOCATION_WRITE',
    'UOM_READ', 'UOM_WRITE', 'DISCOUNT_READ', 'DISCOUNT_WRITE',
    'DAMAGE_LOSS_READ', 'DAMAGE_LOSS_WRITE', 'STOCK_CHECK_READ'
)
ON CONFLICT DO NOTHING;

-- ORG_ADMIN: Full organization access (excludes platform-only permissions)
INSERT INTO role_permissions (role_id, permission_id)
SELECT '22222222-2222-2222-2222-000000000002', id FROM permissions
WHERE name IN (
    'ORG_READ', 'ORG_WRITE', 'STORE_READ', 'STORE_WRITE',
    'PRODUCT_READ', 'PRODUCT_WRITE', 'COST_READ', 'MARGIN_READ',
    'USER_READ', 'USER_WRITE', 'USER_INVITE', 'ROLE_READ', 'ROLE_WRITE',
    'INVENTORY_ITEM_READ', 'INVENTORY_ITEM_WRITE', 'STOCK_ADJUST', 'CYCLE_COUNT', 'TRANSFER_CREATE', 'TRANSFER_APPROVE',
    'PO_READ', 'PO_WRITE', 'PO_APPROVE', 'RECEIVING_CREATE',
    'SALE_READ', 'SALE_WRITE', 'VOID_SALE', 'REFUND_APPROVE', 'PRICE_OVERRIDE', 'DISCOUNT_APPLY',
    'CASH_DRAWER_READ', 'CASH_DRAWER_WRITE', 'END_OF_DAY',
    'REPORT_READ', 'REPORT_FINANCIAL', 'REPORT_INVENTORY',
    'CATEGORY_READ', 'CATEGORY_WRITE', 'BRAND_READ', 'BRAND_WRITE',
    'SUPPLIER_READ', 'SUPPLIER_WRITE', 'LOCATION_READ', 'LOCATION_WRITE',
    'UOM_READ', 'UOM_WRITE', 'DISCOUNT_READ', 'DISCOUNT_WRITE',
    'DAMAGE_LOSS_READ', 'DAMAGE_LOSS_WRITE', 'STOCK_CHECK_READ'
)
ON CONFLICT DO NOTHING;

-- STORE_MANAGER: Full store access
INSERT INTO role_permissions (role_id, permission_id)
SELECT '22222222-2222-2222-2222-000000000003', id FROM permissions
WHERE name IN (
    'STORE_READ', 'STORE_WRITE',
    'PRODUCT_READ', 'PRODUCT_WRITE', 'COST_READ', 'MARGIN_READ',
    'USER_READ', 'USER_WRITE', 'USER_INVITE', 'ROLE_READ',
    'INVENTORY_ITEM_READ', 'INVENTORY_ITEM_WRITE', 'STOCK_ADJUST', 'CYCLE_COUNT', 'TRANSFER_CREATE', 'TRANSFER_APPROVE',
    'PO_READ', 'PO_WRITE', 'PO_APPROVE', 'RECEIVING_CREATE',
    'SALE_READ', 'SALE_WRITE', 'VOID_SALE', 'REFUND_APPROVE', 'PRICE_OVERRIDE', 'DISCOUNT_APPLY',
    'CASH_DRAWER_READ', 'CASH_DRAWER_WRITE', 'END_OF_DAY',
    'REPORT_READ', 'REPORT_FINANCIAL', 'REPORT_INVENTORY',
    'CATEGORY_READ', 'CATEGORY_WRITE', 'BRAND_READ', 'BRAND_WRITE',
    'SUPPLIER_READ', 'SUPPLIER_WRITE', 'LOCATION_READ', 'LOCATION_WRITE',
    'UOM_READ', 'UOM_WRITE', 'DISCOUNT_READ', 'DISCOUNT_WRITE',
    'DAMAGE_LOSS_READ', 'DAMAGE_LOSS_WRITE', 'STOCK_CHECK_READ'
)
ON CONFLICT DO NOTHING;

-- SHIFT_LEAD: Shift supervisor permissions
INSERT INTO role_permissions (role_id, permission_id)
SELECT '22222222-2222-2222-2222-000000000004', id FROM permissions
WHERE name IN (
    'STORE_READ',
    'PRODUCT_READ', 'COST_READ',
    'USER_READ',
    'INVENTORY_ITEM_READ', 'STOCK_ADJUST', 'CYCLE_COUNT',
    'PO_READ', 'RECEIVING_CREATE',
    'SALE_READ', 'SALE_WRITE', 'VOID_SALE', 'PRICE_OVERRIDE', 'DISCOUNT_APPLY',
    'CASH_DRAWER_READ', 'CASH_DRAWER_WRITE', 'END_OF_DAY',
    'REPORT_READ',
    'CATEGORY_READ', 'BRAND_READ', 'SUPPLIER_READ', 'LOCATION_READ', 'UOM_READ',
    'DISCOUNT_READ', 'DAMAGE_LOSS_READ', 'DAMAGE_LOSS_WRITE', 'STOCK_CHECK_READ'
)
ON CONFLICT DO NOTHING;

-- CASHIER: POS operations
INSERT INTO role_permissions (role_id, permission_id)
SELECT '22222222-2222-2222-2222-000000000005', id FROM permissions
WHERE name IN (
    'STORE_READ',
    'PRODUCT_READ',
    'INVENTORY_ITEM_READ',
    'SALE_READ', 'SALE_WRITE', 'DISCOUNT_APPLY',
    'CASH_DRAWER_READ',
    'CATEGORY_READ', 'BRAND_READ', 'UOM_READ',
    'DISCOUNT_READ', 'STOCK_CHECK_READ'
)
ON CONFLICT DO NOTHING;

-- INVENTORY_SPECIALIST: Stock management
INSERT INTO role_permissions (role_id, permission_id)
SELECT '22222222-2222-2222-2222-000000000006', id FROM permissions
WHERE name IN (
    'STORE_READ',
    'PRODUCT_READ', 'PRODUCT_WRITE',
    'INVENTORY_ITEM_READ', 'INVENTORY_ITEM_WRITE', 'STOCK_ADJUST', 'CYCLE_COUNT', 'TRANSFER_CREATE',
    'PO_READ', 'RECEIVING_CREATE',
    'REPORT_INVENTORY',
    'CATEGORY_READ', 'BRAND_READ', 'SUPPLIER_READ', 'LOCATION_READ', 'LOCATION_WRITE', 'UOM_READ',
    'DAMAGE_LOSS_READ', 'DAMAGE_LOSS_WRITE', 'STOCK_CHECK_READ'
)
ON CONFLICT DO NOTHING;

-- PURCHASING_AGENT: Vendor/PO management
INSERT INTO role_permissions (role_id, permission_id)
SELECT '22222222-2222-2222-2222-000000000007', id FROM permissions
WHERE name IN (
    'STORE_READ',
    'PRODUCT_READ', 'COST_READ',
    'INVENTORY_ITEM_READ',
    'PO_READ', 'PO_WRITE', 'RECEIVING_CREATE',
    'REPORT_INVENTORY',
    'CATEGORY_READ', 'BRAND_READ', 'SUPPLIER_READ', 'SUPPLIER_WRITE', 'LOCATION_READ', 'UOM_READ',
    'STOCK_CHECK_READ'
)
ON CONFLICT DO NOTHING;

-- ACCOUNTANT: Financial reporting
INSERT INTO role_permissions (role_id, permission_id)
SELECT '22222222-2222-2222-2222-000000000008', id FROM permissions
WHERE name IN (
    'ORG_READ', 'STORE_READ',
    'PRODUCT_READ', 'COST_READ', 'MARGIN_READ',
    'INVENTORY_ITEM_READ',
    'PO_READ',
    'SALE_READ',
    'CASH_DRAWER_READ',
    'REPORT_READ', 'REPORT_FINANCIAL', 'REPORT_INVENTORY',
    'CATEGORY_READ', 'BRAND_READ', 'SUPPLIER_READ', 'LOCATION_READ', 'UOM_READ',
    'DISCOUNT_READ', 'DAMAGE_LOSS_READ', 'STOCK_CHECK_READ'
)
ON CONFLICT DO NOTHING;

-- STAFF: General read access
INSERT INTO role_permissions (role_id, permission_id)
SELECT '22222222-2222-2222-2222-000000000009', id FROM permissions
WHERE name IN (
    'STORE_READ',
    'PRODUCT_READ',
    'INVENTORY_ITEM_READ',
    'CATEGORY_READ', 'BRAND_READ', 'LOCATION_READ', 'UOM_READ',
    'DISCOUNT_READ', 'STOCK_CHECK_READ'
)
ON CONFLICT DO NOTHING;

--rollback DELETE FROM role_permissions WHERE role_id IN (SELECT id FROM roles WHERE created_by = 'liquibase');
